### PR TITLE
fix: Custom headers

### PR DESCRIPTION
**Pull request by kuisathaverat**
## What does this PR do?

* It adds a new custom header to the APM Server
## Why is it important?

This is a new requirement for the RUM agent.

Related to https://github.com/elastic/apm-agent-rum-js/pull/1055/files#diff-b8cd439b02c2daaa54b6f62cdf87fce19b70de0e1dea956b7bf054e775dc0f1dR46

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]

**Comment by axw** [comment]
thank you @kuisathaverat ! apm-server is still failing on 7.14, looks like this needs to be backported there too

**Comment by axw** [comment]
@Mergifyio backport 7.14

**Comment by axw** [comment]
ah I guess 7.14 uses the 7.x branch? the backport hasn't merged there yet

**Comment by kuisathaverat** [comment]
the backport is https://github.com/elastic/apm-integration-testing/pull/1216

**Pull request merged**
