### PR TITLE
update v1 test configuration

### PR DESCRIPTION
**Pull request by graphaelli**
Use released stack container images where possible and update tests to only run those compatible with v1.

## For pull requests and on push

this will test:

apm-server and elasticsearch 6.5 released container images

vs

nodejs agent built from 1.x
python agent build from 3.x
ruby agent built from 1.x 

## For periodic version tests

this will test:

apm-server and elasticsearch 6.2-6.6 released container images + 6.7 snapshots

vs 

nodejs agent latest version 1 release
python agent latest version 2.0 & 3.0 releases
ruby agent built from 1.x

### CODE REVIEW

**Comment by graphaelli** [comment]
This started the environment with:
```
python scripts/compose.py start 6.5  --no-apm-server-dashboards --no-apm-server-self-instrument --with-agent-rumjs --with-agent-go-net-http --with-agent-nodejs-express --with-agent-python-django --with-agent-python-flask --with-agent-ruby-rails --with-agent-java-spring --force-build
```

which only has the right elasticsearch version - all of the agents will pull latest, which isn't right for 6.x v1.

**Comment by graphaelli** [comment]
Now things are starting as expected, with:
```
python scripts/compose.py start 6.5 --release --nodejs-agent-package=elastic/apm-agent-nodejs#1.x --python-agent-package=git+https://github.com/elastic/apm-agent-python.git@3.x --ruby-agent-version-state=github --ruby-agent-version=1.x --no-apm-server-dashboards --no-apm-server-self-instrument --with-agent-nodejs-express --with-agent-python-django --with-agent-python-flask --with-agent-ruby-rails --force-build
```
*todo: add `--no-kibana`*

Unfortunately there seems to be either a real issue or the ruby agent healthcheck filtering isn't configured correctly, will try to reproduce locally:

```
15:01:12 tests/agent/test_ruby.py::test_conc_req_rails_foobar PASSED              [  5%]
15:01:20 tests/agent/test_ruby.py::test_conc_req_rails PASSED                     [ 10%]
15:01:23 tests/agent/test_ruby.py::test_rails_error PASSED                        [ 15%]
15:01:35 tests/agent/test_ruby.py::test_req_rails FAILED                          [ 21%]
15:01:38 tests/agent/test_python.py::test_req_flask PASSED                        [ 26%]
15:01:57 tests/agent/test_python.py::test_concurrent_req_django_foobar PASSED     [ 31%]
15:01:58 tests/agent/test_python.py::test_req_django PASSED                       [ 36%]
15:02:13 tests/agent/test_python.py::test_concurrent_req_flask PASSED             [ 42%]
15:02:23 tests/agent/test_python.py::test_concurrent_req_flask_foobar PASSED      [ 47%]
15:02:26 tests/agent/test_python.py::test_django_error PASSED                     [ 52%]
15:02:44 tests/agent/test_python.py::test_concurrent_req_django PASSED            [ 57%]
15:02:47 tests/agent/test_python.py::test_flask_error PASSED                      [ 63%]
15:02:47 tests/kibana/test_integration.py::test_sidebar SKIPPED                   [ 68%]
15:03:02 tests/agent/test_nodejs.py::test_conc_req_node_foobar PASSED             [ 73%]
15:03:04 tests/agent/test_nodejs.py::test_express_error PASSED                    [ 78%]
15:03:12 tests/agent/test_nodejs.py::test_conc_req_express PASSED                 [ 84%]
15:03:14 tests/agent/test_nodejs.py::test_request_express PASSED                  [ 89%]
15:03:17 tests/server/test_transaction.py::test_process_transaction PASSED        [ 94%]
15:04:04 tests/agent/test_multiple_agents.py::test_conc_req_all_agents PASSED     [100%]
```

**Comment by graphaelli** [comment]
@mikker / @simitt  I could use a hand with this one.  The ruby agent tests for v1 consistently fail for me locally using the environment launched as above and run with `./venv/bin/pytest -v -s -x`, but in inconsistent ways.  Sometimes there will be 999 documents from `/foo`, sometimes 1000 but also 820 from `/bar`, and other combinations.

Gemfile.lock says the version is:
```
GIT
  remote: https://github.com/elastic/apm-agent-ruby.git
  revision: dcce7440f9c9ca31f0dfae969d7345825dc3922f
  branch: 1.x
  specs:
    elastic-apm (1.1.0)
      concurrent-ruby (~> 1.0.0)
```

**Comment by simitt** [comment]
@graphaelli tests went through locally with the change I pushed. The ruby agent v1 uses a different config option to ensure documents were pushed to the server.

**Pull request merged**
