### PR TITLE
Add test for validating Typescript interfaces against sample docs

### PR DESCRIPTION
**Pull request by sqren**
Closes: elastic/kibana#31925
Note: This is WIP and depends on https://github.com/elastic/kibana/pull/32918

This adds a lightweight integration test between APM UI (Kibana) and APM Server. The test will download sample documents from APM Server and validate them against Typescript interfaces located in Kibana. 
It might be advantageous to package this up as a Docker image - not sure if it's worth it.

### CODE REVIEW

**Comment by kuisathaverat** [comment]
the CI will use a docker image to run the thing, so I have to make it on some way, don't worry about it

**Comment by sqren** [comment]
@kuisathaverat Do you know why the build is failing?

**Comment by kuisathaverat** [comment]
@sqren the failure is not related to this PR.

**Comment by kuisathaverat** [comment]
jenkins run the tests please

**Pull request merged**
