### PR TITLE
ci(jenkins): use agentMapping step

### PR DESCRIPTION
**Pull request by v1v**
## Highlights
- Use the `agentMapping ` step which already contains methods to those maps.

## Tasks
- [x] Backport to the other branches. As agreed we won't backport it
- [x] Revert https://github.com/elastic/apm-integration-testing/pull/510/commits/f2a5485b4cadc8152d5fac1ecec0bd5cb0352cf9

### CODE REVIEW

**Comment by kuisathaverat** [comment]
@v1v we can keep old branches as they are, I think we no need to backport this

**Comment by mdelapenya** [comment]
Is `its` a good name? I would choose a more representative one

**Comment by v1v** [comment]
What name? I chose that one as we normally use `ITs`, so it was a good candidate, but happy to rename it

**Comment by mdelapenya** [comment]
The `its` step is simply selecting the argument/fields for agents, right? like an agent mapping/facade/selector...

image

**Comment by mdelapenya** [comment]
I like the name ❤️! What I say weird is repeating the word `agent` in the method name. Take a look at those methods:

`agentMapping.ymlFiles` Vs `agentMapping.agentYamlVar` or `agentMapping.mapAgentsIDs`

What do you think of renaming the methods to:

```diff
- agentMapping.mapAgentsIDs
+ agentMapping.mapIDs

- agentMapping.agentYamlVar
+ agentMapping.ymlVars
```

**Comment by v1v** [comment]
jenkins run the tests please

**Pull request merged**
