### PR TITLE
Increase java agent buffer

### PR DESCRIPTION
**Pull request by eyalkoren**
Trying to battle the Java agent failures...

### CODE REVIEW

**Comment by eyalkoren** [comment]
@kuisathaverat the failure in https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1704/display/redirect is in the `java:github;v1.0.1#6.6;--release` test. Is this being tested through the 6.x branch? How can I test it?

**Comment by kuisathaverat** [comment]
At the beginning of the log of the [failed stage](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-test-axis-pipeline/detail/apm-integration-test-axis-pipeline/1704/pipeline/67), you have the parameters have passed to the compose.py it is using 6.6 releases

```
[2019-03-19T09:08:03.467Z] ELASTIC_STACK_VERSION=6.6 --release
[2019-03-19T09:08:03.467Z] APM_SERVER_BRANCH_VERSION=6.6
[2019-03-19T09:08:03.467Z] APM_SERVER_BRANCH_TYPE=--release
[2019-03-19T09:08:03.467Z] BUILD_OPTS= 
[2019-03-19T09:08:03.467Z] test -d /var/lib/jenkins/workspace/apm-integration-test-axis-pipelinevenv-2236 || virtualenv -q --python=python3 /var/lib/jenkins/workspace/apm-integration-test-axis-pipelinevenv-2236;\
[2019-03-19T09:08:03.467Z] pip install -q -r requirements.txt;\
[2019-03-19T09:08:03.467Z] touch /var/lib/jenkins/workspace/apm-integration-test-axis-pipelinevenv-2236;\
[2019-03-19T09:08:03.467Z] 
[2019-03-19T09:08:25.578Z] make start-env
[2019-03-19T09:08:25.578Z] make[1]: Entering directory '/var/lib/jenkins/workspace/apm-integration-test-axis-pipeline/src/github.com/elastic/apm-integration-testing'
[2019-03-19T09:08:25.578Z] test -d /var/lib/jenkins/workspace/apm-integration-test-axis-pipelinevenv-2236 || virtualenv -q --python=python3 /var/lib/jenkins/workspace/apm-integration-test-axis-pipelinevenv-2236;\
[2019-03-19T09:08:25.578Z] pip install -q -r requirements.txt;\
[2019-03-19T09:08:25.578Z] touch /var/lib/jenkins/workspace/apm-integration-test-axis-pipelinevenv-2236;\
[2019-03-19T09:08:25.578Z] 
[2019-03-19T09:08:25.578Z] python scripts/compose.py start 6.6 --release   --java-agent-version='v1.0.1' --no-apm-server-dashboards --no-apm-server-self-instrument --no-kibana --with-agent-java-spring --force-build
[2019-03-19T09:08:25.578Z] Building agent-java-spring
[2019-03-19T09:08:25.578Z] Step 1/17 : FROM maven:3.5.3-jdk-10
```

This is the exact compose command

`python scripts/compose.py start 6.6 --release   --java-agent-version='v1.0.1' --no-apm-server-dashboards --no-apm-server-self-instrument --no-kibana --with-agent-java-spring --force-build`

These were containers running

```
[2019-03-19T09:12:54.434Z] *******************************************************
[2019-03-19T09:12:54.434Z] ***************Docker Containers Summary***************
[2019-03-19T09:12:54.434Z] *******************************************************
[2019-03-19T09:12:54.434Z] CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                    PORTS                                                NAMES
[2019-03-19T09:12:54.435Z] 55e8d5efff78        docker.elastic.co/apm/apm-server:6.6.1                "/usr/local/bin/dock…"   7 seconds ago       Up 5 seconds (healthy)    127.0.0.1:6060->6060/tcp, 127.0.0.1:8200->8200/tcp   localtesting_6.6.1_apm-server
[2019-03-19T09:12:54.435Z] c446181dd68f        docker.elastic.co/elasticsearch/elasticsearch:6.6.1   "/usr/local/bin/dock…"   42 seconds ago      Up 37 seconds (healthy)   127.0.0.1:9200->9200/tcp, 9300/tcp                   localtesting_6.6.1_elasticsearch
[2019-03-19T09:12:54.435Z] e02be3d72bad        apm-integration-testing_agent-java-spring             "java -javaagent:/ap…"   42 seconds ago      Up 38 seconds (healthy)   127.0.0.1:8090->8090/tcp                             javaspring
```

You can search the logs and the inspect Docker info on the [build artifacts](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-test-axis-pipeline/detail/apm-integration-test-axis-pipeline/1704/artifacts) all are in the folder `docker-info/java-github/v1_0_1-6_6/_release/`, they are identifies by the Docker ID, There, you have also the [docker-compose file](https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1704/artifact/docker-info/java-github/v1_0_1-6_6/_release/docker-compose.yml) used for the test so you can use the same containers 
 
* [docker-containers.txt](https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1704/artifact/docker-info/java-github/v1_0_1-6_6/_release/docker-containers.txt)
* [55e8d5efff78-cmd.txt](https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1704/artifact/docker-info/java-github/v1_0_1-6_6/_release/55e8d5efff78-cmd.txt)
* [55e8d5efff78-inspect.json](https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1704/artifact/docker-info/java-github/v1_0_1-6_6/_release/55e8d5efff78-inspect.json)
* [55e8d5efff78.log](https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1704/artifact/docker-info/java-github/v1_0_1-6_6/_release/55e8d5efff78.log)
* [c446181dd68f-cmd.txt](https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1704/artifact/docker-info/java-github/v1_0_1-6_6/_release/c446181dd68f-cmd.txt)
* [c446181dd68f-inspect.json](https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1704/artifact/docker-info/java-github/v1_0_1-6_6/_release/c446181dd68f-inspect.json)
* [c446181dd68f.log](https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1704/artifact/docker-info/java-github/v1_0_1-6_6/_release/c446181dd68f.log)
* [e02be3d72bad-cmd.txt](https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1704/artifact/docker-info/java-github/v1_0_1-6_6/_release/e02be3d72bad-cmd.txt)
* [/e02be3d72bad-inspect.json](https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1704/artifact/docker-info/java-github/v1_0_1-6_6/_release/e02be3d72bad-inspect.json)
* [/e02be3d72bad.log](https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1704/artifact/docker-info/java-github/v1_0_1-6_6/_release/e02be3d72bad.log)

The data in Elasticsearch is also there [tests/results/data-test_concurrent_req_java_spring.json](https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1704/artifact/tests/results/data-test_concurrent_req_java_spring.json)

the following command count the documents by type

`cat data-test_concurrent_req_java_spring.json |jq '.hits.hits[]._source.processor.event'|sort|uniq -c`

cc @graphaelli we store whole documents because size does not apply to each index only to the whole search that returns 3 hits, but I think is fine, in this case, it is needed

**Comment by kuisathaverat** [comment]
```
cat /Users/inifc/Downloads/data-test_concurrent_req_java_spring.json |jq cat /Users/inifc/Downloads/data-test_concurrent_req_java_spring.json |jq '.hits.hits[]._source| "\(.processor.event) \(.transaction.name)"'|sort|uniq -c

   3 "metric null"
2000 "span null"
2000 "transaction GreetingController#foo"
```

**Comment by kuisathaverat** [comment]
I think that the data is taking more than 60 seconds to be available for search on Elasticsearch

Timestamps of span documents

`cat data-test_concurrent_req_java_spring.json |jq '.hits.hits[]._source|select(.processor.event=="span")."@timestamp"'|sort`

```
"2019-03-19T09:18:11.484Z"
"2019-03-19T09:18:11.487Z"
"2019-03-19T09:18:11.488Z"
"2019-03-19T09:18:11.491Z"
"2019-03-19T09:18:11.511Z"
"2019-03-19T09:18:11.525Z"
"2019-03-19T09:18:11.528Z"
"2019-03-19T09:18:11.530Z"
"2019-03-19T09:18:11.533Z"
"2019-03-19T09:18:11.549Z"
"2019-03-19T09:18:11.553Z"
....
"2019-03-19T09:18:22.935Z"
"2019-03-19T09:18:22.936Z"
"2019-03-19T09:18:22.945Z"
"2019-03-19T09:18:22.945Z"
"2019-03-19T09:18:22.947Z"
"2019-03-19T09:18:22.947Z"
"2019-03-19T09:18:22.964Z"
```

Documents ingested per second 

`cat /Users/inifc/Downloads/data-test_concurrent_req_java_spring.json |jq -r '.hits.hits[]._source|select(.processor.event=="span")| ."@timestamp"'|sort|cut -d "." -f 1| uniq -c`

```
 100 2019-03-19T09:18:11
 260 2019-03-19T09:18:12
 236 2019-03-19T09:18:13
 180 2019-03-19T09:18:14
 175 2019-03-19T09:18:15
  49 2019-03-19T09:18:16
  72 2019-03-19T09:18:18
 214 2019-03-19T09:18:19
 318 2019-03-19T09:18:20
 201 2019-03-19T09:18:21
 195 2019-03-19T09:18:22
```

**Comment by kuisathaverat** [comment]
I am going to run this PR and the other several times to see if the issue disappears

**Comment by kuisathaverat** [comment]
@eyalkoren increase the buffer minimizes the issue, but it still happens, the worst thing is that there are no errors on the logs, so we do not know if the document went from the agent to the server, Is there any way to see a trace of documents sent to the APM server on logs?

**Comment by eyalkoren** [comment]
@kuisathaverat all failures that I saw prior to this change are with exactly one missing transaction (1999 instead of 2000 or 1374 instead of 1375). With only the changes in this PR, did you see that reproduced?

**Comment by kuisathaverat** [comment]
@eyalkoren I am afraid so, two times in a week, on the other PR I have opened for test it with another change (a 5 seconds sleep between test). We have launched about 30 builds between both PRs, so It does not fail too much but it is still there. The only thing we can make to see where is the lost document it is to put a proxy between the agent and the server, and another proxy between the server and Elasticsearch to log the messages, I will try to instrument it on another PR and test it for a week or so.

**Comment by eyalkoren** [comment]
@kuisathaverat thanks a lot! Let's talk and see how we tackle it together.

**Pull request merged**
