### PR TITLE
add --elasticsearch-data-dir option

### PR DESCRIPTION
**Pull request by graphaelli**
To enable upgrade testing, like:

```
./scripts/compose.py start 6.6 --elasticsearch-data-dir "" ...
# don't remove any volumes here
./scripts/compose.py start 7.0.0 --elasticsearch-data-dir "" ...
```

@beniwohli I'm pretty sure this versioned data dir has been here for a long time, do you recall why or if this is a bad idea?  I hesitate to add yet another option to control this but can do it if there's a risk this will cause people problems.

### CODE REVIEW

**Comment by graphaelli** [comment]
It occurred to me that it was probably so users didn't have to wipe their data volume between starts.  I wonder though if that's even more confusing since sometimes old data will show up and sometimes it won't (when relaunching the same version later).

**Comment by beniwohli** [comment]
The main reason I introduced versioned directories was to avoid breakage when jumping between major versions. e.g. running 6.x, then master, then 6.x again could break because master updates some system indexes that then don't work anymore on 6.x.

TBH, I think we should retain versioned directories. compose.py is brittle enough as it is, and this would introduce another failure point with hard to understand error messages. I agree that adding _another_ flag is not great. Maybe we have to accept the fact that we can't test _every_ possible scenario under the sun with compose.py.

**Comment by graphaelli** [comment]
Fair enough.  Upgrade testing is really important so I'll switch this to add a new flag and leave the default data dirs versioned.

**Comment by graphaelli** [comment]
done, ready again for review

**Comment by graphaelli** [comment]
jenkins, retest this please

**Comment by graphaelli** [comment]
the test failures seem to be unrelated to this change.

**Comment by graphaelli** [comment]
jenkins, retest this please

**Comment by graphaelli** [comment]
spoke with beniwohli, he's 👍

**Pull request merged**
