### PR TITLE
Fix apm integration with elastic-agent

### PR DESCRIPTION
**Pull request by simitt**
## What does this PR do?
fixes the `--apm-server-managed` command to add an apm integration to the fleet-server default policy.

### CODE REVIEW

**Comment by simitt** [comment]
@kuisathaverat any idea what's going on with the CI? I don't think the failure is related to the change.

**Comment by kuisathaverat** [comment]
yesterday was a tough day

```
[2021-06-08T09:56:58.369Z] + mvn -q --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dhttps.protocols=TLSv1.2 -Dmaven.wagon.http.retryHandler.count=10 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.repo.local=/root/.m2/repository install

[2021-06-08T09:57:00.694Z] [ERROR] [ERROR] Some problems were encountered while processing the POMs:

[2021-06-08T09:57:00.695Z] [ERROR] Non-resolvable import POM: Could not transfer artifact org.testcontainers:testcontainers-bom:pom:1.15.2 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/testcontainers/testcontainers-bom/1.15.2/testcontainers-bom-1.15.2.pom 503 Service Unavailable @ line 515, column 25

[2021-06-08T09:57:00.695Z]  @ 

[2021-06-08T09:57:00.695Z] [ERROR] The build could not read 1 project -> [Help 1]

[2021-06-08T09:57:00.695Z] [ERROR]   

[2021-06-08T09:57:00.695Z] [ERROR]   The project co.elastic.apm:apm-agent-parent:1.24.1-SNAPSHOT (/agent/apm-agent-java/pom.xml) has 1 error

[2021-06-08T09:57:00.695Z] [ERROR]     Non-resolvable import POM: Could not transfer artifact org.testcontainers:testcontainers-bom:pom:1.15.2 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/testcontainers/testcontainers-bom/1.15.2/testcontainers-bom-1.15.2.pom 503 Service Unavailable @ line 515, column 25 -> [Help 2]

[2021-06-08T09:57:00.695Z] [ERROR] 

[2021-06-08T09:57:00.695Z] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[2021-06-08T09:57:00.695Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.

[2021-06-08T09:57:00.695Z] [ERROR] 

[2021-06-08T09:57:00.695Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:

[2021-06-08T09:57:00.695Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

[2021-06-08T09:57:00.695Z] [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

[2021-06-08T09:57:00.953Z] 

[2021-06-08T09:57:00.954Z] ERROR: for agent-rumjs  (<Service: agent-rumjs>, 'ADD failed: failed to GET https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 with status 503 Service Unavailable: <?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"\n "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n<html>\n  <head>\n    <title>503 Service Unavailable</title>\n  </head>\n  <body>\n    <h1>Error 503 Service Unavailable</h1>\n    <p>Service Unavailable</p>\n    <h3>Guru Mediation:</h3>\n    <p>Details: cache-mdw17326-MDW 1623146207 978732852</p>\n    <hr>\n    <p>Varnish cache server</p>\n  </body>\n</html>')

[2021-06-08T09:57:00.954Z] 

[2021-06-08T09:57:00.954Z] ERROR: for agent-java-spring  (<Service: agent-java-spring>, 'The command \'/bin/sh -c ./maven-package.sh "${JAVA_AGENT_BUILT_VERSION}"\' returned a non-zero code: 1')

[2021-06-08T09:57:00.954Z] Service 'agent-java-spring' failed to build: The command '/bin/sh -c ./maven-package.sh "${JAVA_AGENT_BUILT_VERSION}"' returned a non-zero code: 1
```

**Pull request merged**
