### PR TITLE
fix: signal internal Node.js workload script to disable

### PR DESCRIPTION
**Pull request by watson**
Currently `--no-opbeans-node-loadgen` doesn't have any effect on opbeans-node as it's not using the regular loadgen container.

The idea of the PR is to repurpose this config option and instead use it to set an environment variable which the internal loadgen script can see and know if it should run or not.

### CODE REVIEW

**Comment by watson** [comment]
@v1v Do you know why the tests are failing? They seem unrelated, but I'm not sure

**Comment by v1v** [comment]
It seems a test failure in the downstream job:
- https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-test-axis-pipeline/detail/apm-integration-test-axis-pipeline/736/tests

Is that what you meant?

**Comment by watson** [comment]
Yes. So it's not related to this PR? I just wasn't sure if we safely merge this or if it would break master

**Comment by v1v** [comment]
jenkins run the tests please

**Comment by v1v** [comment]
I just added some changes in the UTs to fix that issue (see https://github.com/elastic/apm-integration-testing/pull/490/commits/21c92526ed654a82e4037903f17a609d61b732fc). Besides, I raised https://github.com/elastic/apm-integration-testing/pull/493 to help to analise this kind of issues in the future.

**Pull request merged**
