### PR TITLE
feat: dotnet agent uses Elastic.Apm.NetCoreAll and enable --opbeans-dotnet-version

### PR DESCRIPTION
**Pull request by v1v**
This is caused by https://github.com/elastic/apm-agent-dotnet/pull/371

Depends on https://github.com/elastic/opbeans-dotnet/pull/11

## Highlight
- The csproj has been changed in the above PR, let's change in the opbeans and dotnet images to be able to parse the version with some backward compatibility.
- enable `--opbeans-dotnet-version` flag as it was not implemented though.

## How to test the opbeans locally?
- Check out this PR
- Edit `docker/opbeans/dotnet/Dockerfile`
- Change the below env variables
```
ENV OPBEANS_DOTNET_REPO=v1v/opbeans-dotnet
ENV OPBEANS_DOTNET_BRANCH=feature/rename
```
- Run the below docker commands
```
docker build --build-arg DOTNET_AGENT_REPO=gregkalapos/apm-agent-dotnet --build-arg DOTNET_AGENT_BRANCH=renaming --tag opbeans-dotnet-test docker/opbeans/dotnet/
docker run --rm -ti -p 28080:80 opbeans-dotnet-test
```
- Open http://localhost:28080

## How to test the dotnet app locally?
- Check out this PR
- Run the below docker commands
```
docker build --build-arg DOTNET_AGENT_REPO=gregkalapos/apm-agent-dotnet --build-arg DOTNET_AGENT_BRANCH=renaming --tag dotnet-test docker/dotnet
docker run --rm -ti -p 28100:8100 dotnet-test:latest
```
- Open http://localhost:28100

## How to run the ITs locally?
- Check out this PR
- Edit `docker/opbeans/dotnet/Dockerfile`
- Change the below env variables
```
ENV OPBEANS_DOTNET_REPO=v1v/opbeans-dotnet
ENV OPBEANS_DOTNET_BRANCH=feature/rename
```
- Run the below commands
```
./scripts/compose.py start master --with-opbeans-dotnet --with-agent-dotnet \
    --opbeans-dotnet-agent-branch renaming \
    --opbeans-dotnet-agent-repo gregkalapos/apm-agent-dotnet  \
    --dotnet-agent-repo gregkalapos/apm-agent-dotnet \
    --dotnet-agent-version renaming
 make docker-test-agent-dotnet
```
```
tests/agent/test_dotnet.py::test_concurrent_req_dotnet_foobar PASSED     [ 25%]
tests/agent/test_dotnet.py::test_dotnet_error PASSED                     [ 50%]
tests/agent/test_dotnet.py::test_req_dotnet PASSED                       [ 75%]
tests/agent/test_dotnet.py::test_concurrent_req_dotnet PASSED            [100%]
```

### CODE REVIEW

**Comment by gregkalapos** [comment]
Not sure this is enough - we also renamed [this method](https://github.com/elastic/apm-integration-testing/blob/master/docker/dotnet/aspnetcore/Startup.cs#L23). For the project in this repo I already have a workaround, but for the opbeans-dotnet project it's not that easy. 

Will follow up soon.

**Comment by v1v** [comment]
## CI executions
- [build](https://apm-ci.elastic.co/job/apm-integration-test-axis-pipeline/1556/console) 
```
python scripts/compose.py start 8.0.0   --apm-server-build https://github.com/elastic/apm-server.git@master --build-parallel --dotnet-agent-version=master --no-apm-server-dashboards --no-apm-server-self-instrument --no-kibana --with-agent-dotnet --force-build
...

14:00:49  + DOTNET_AGENT_VERSION=1.0.0-beta1
14:00:49  + dotnet add package Elastic.Apm.NetCoreAll -v 1.0.0-beta1
...
14:00:54  + sed -ibck 's#\(<PackageReference Include="Elastic\.Apm\.NetCoreAll" Version=\)"\(.*\)"#\1"1.0.0-beta1"#' TestAspNetCoreApp.csproj
...
```

```

**Comment by v1v** [comment]
It's also required to backport this PR onto the 7.x branch

**Comment by v1v** [comment]
> Not sure this helps, but you could also build it from this release in older branches.
It might be possible, although I do prefer to keep `7.x` align with the upcoming `7.3` release. Does it sound good?

**Comment by gregkalapos** [comment]
> Not sure this helps, but you could also build it from this release in older branches.
> It might be possible, although I do prefer to keep `7.x` align with the upcoming `7.3` release. Does it sound good?

Sure, sure! It was just more like a hint - I'm definitely ok with that.

**Pull request merged**
