### PR TITLE
fix: update flake8 and deps to work with Python 3.8+

### PR DESCRIPTION
**Pull request by trentm**
This fixes 'make lint' when one has Python 3.8 or later
(https://github.com/PyCQA/pyflakes/issues/367), but updating to the
latest flake8 and its deps. Note that flake8 3.9.0 dropped support
for Python 3.4
(https://flake8.pycqa.org/en/latest/release-notes/3.9.0.html)

In my case I have Python 3.9. Presumably CI is using a Python version less than 3.8?
Is support for Python 3.4 required? If so, then we can't upgrade the flake8 v3.9.0.

Before:

```
% make lint
test -d ./venv || virtualenv -q --python=python3 ./venv;\
	source ./venv/bin/activate || exit 1;\
	pip install -q -r requirements.txt;\
	touch ./venv;\

flake8 --ignore=D100,D101,D102,D103,D104,D105,D106,D107,D200,D205,D400,D401,D403,W504  tests/ scripts/compose.py scripts/modules
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 451, in run_check
    return plugin["plugin"](**arguments)
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/plugins/pyflakes.py", line 99, in __init__
    super(FlakesChecker, self).__init__(
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 497, in __init__
    self.handleChildren(tree)
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 870, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 700, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 682, in _run_checks
    return checker.run_checks()
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 612, in run_checks
    self.run_ast_checks()
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 513, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 456, in run_check
    raise exceptions.PluginExecutionFailed(
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/exceptions.py", line 86, in __init__
    self.original_exception = kwargs.pop("exception")
KeyError: 'exception'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/trentm/tm/apm-integration-testing/venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/main/application.py", line 412, in run
    self._run(argv)
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/main/application.py", line 400, in _run
    self.run_checks()
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/main/application.py", line 318, in run_checks
    self.file_checker_manager.run()
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 338, in run
    self.run_parallel()
  File "/Users/trentm/tm/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 302, in run_parallel
    for ret in pool_map:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
KeyError: 'exception'
make: *** [lint] Error 1
```

After:

```
% make lint
test -d ./venv || virtualenv -q --python=python3 ./venv;\
	source ./venv/bin/activate || exit 1;\
	pip install -q -r requirements.txt;\
	touch ./venv;\

flake8 --ignore=D100,D101,D102,D103,D104,D105,D106,D107,D200,D205,D400,D401,D403,W504  tests/ scripts/compose.py scripts/modules
```

### CODE REVIEW

**Comment by trentm** [comment]
Is asking `@elastic/observablt-robots` for review on this the appropriate group?

**Review by mdelapenya — APPROVED** [review]
I'd like to check the Python versions before merging, just in case your rationale about Python versions and deps is correct.

Apart from that, LGTM

**Comment by trentm** [comment]
@mdelapenya 

> I'd like to check the Python versions before merging

Thanks. Let me know if you need me to do something for that check. I don't know how to tell what Python version is being used in the build containers.

**Review by cachedout — APPROVED** [review]

**Comment by kuisathaverat** [comment]
the Python version we use depends on the worker OS, for example on Ubuntu 18.04 we have `Python 3.5.3` and on Ubuntu 20.04 we have `Python 3.8.2`. It is weird, I have `Python 3.9.2` on my laptop, if I do not activate the virtual environment before run `make lint` it works perfectly 

```
>rm -fr ./venv

>python --version
Python 3.9.2

>make lint
test -d ./venv || virtualenv -q --python=python3 ./venv;\
	source ./venv/bin/activate || exit 1;\
	pip install -q -r requirements.txt;\
	touch ./venv;\

flake8 --ignore=D100,D101,D102,D103,D104,D105,D106,D107,D200,D205,D400,D401,D403,W504  tests/ scripts/compose.py scripts/modules
```

if I activate the virtual environment before run `make` it fails

```
>. ./venv/bin/activate

>python --version
Python 3.9.2

> make lint
flake8 --ignore=D100,D101,D102,D103,D104,D105,D106,D107,D200,D205,D400,D401,D403,W504  tests/ scripts/compose.py scripts/modules
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 451, in run_check
    return plugin["plugin"](**arguments)
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/plugins/pyflakes.py", line 99, in __init__
    super(FlakesChecker, self).__init__(
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 497, in __init__
    self.handleChildren(tree)
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 870, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 700, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 682, in _run_checks
    return checker.run_checks()
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 612, in run_checks
    self.run_ast_checks()
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 513, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 456, in run_check
    raise exceptions.PluginExecutionFailed(
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/exceptions.py", line 86, in __init__
    self.original_exception = kwargs.pop("exception")
KeyError: 'exception'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/inifc/src/apm-integration-testing/venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/main/application.py", line 412, in run
    self._run(argv)
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/main/application.py", line 400, in _run
    self.run_checks()
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/main/application.py", line 318, in run_checks
    self.file_checker_manager.run()
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 338, in run
    self.run_parallel()
  File "/Users/inifc/src/apm-integration-testing/venv/lib/python3.9/site-packages/flake8/checker.py", line 302, in run_parallel
    for ret in pool_map:
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
KeyError: 'exception'
make: *** [lint] Error 1
```

So the virtual environment is not activated on the makefile as expected on the target `venv`, I will make a PR to fix it

**Review by kuisathaverat — APPROVED** [review]

**Review by v1v — APPROVED** [review]

**Pull request merged**
