### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by bartier**
## What does this PR do?
Fix a single typo in README.md

## Why is it important?
Actually not important, it is just a typo. Please, feel free to edit README.md directly and not approve this PR if it is considered 'too simple' =P

## Related issues
Closes #ISSUE

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @bartier. Thanks for this! We do need you to sign our CLA before we can merge this, though.

**Comment by bartier** [comment]
@cachedout I've already done that with this [link](https://www.elastic.co/pt/contributor-agreement). Is that an automatic process after I completed and downloaded the pdf?

 Can be the pipeline run again? :)

**Comment by bartier** [comment]
@cachedout 

I think there is a error or something in the [pipeline](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-tests/detail/PR-755/3/pipeline):
image
Is there anything I have to do?

**Comment by cachedout** [comment]
jenkins run the tests please

**Comment by cachedout** [comment]
All fixed up and merged. Thanks for the contribution, @bartier !

**Pull request merged**
