### PR TITLE
fix: update chrome and pm2 to fix unhealthy rum instance

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ chrome is changed from stable - unstable.. https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker

+ have updated pm2 to latest because of https://github.com/Unitech/pm2/issues/3266#issuecomment-366917676. 

pm2 daemon was not getting killed after doing these two changes,
+ Memory and CPU was not bound, So if the issue continues to appear we need to either increase the timeout of health check for this specific image.

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
Can anyone help here why the CI is failing? Doesn't seem to be related to the change. @graphaelli @kuisathaverat

**Comment by kuisathaverat** [comment]
The APM server is not started correctly, in those cases, you can relaunch the job to see if it is consistent, I think is not related too. 

```
ERROR: for apm-server  Container "34e0b7b79b03" is unhealthy.
```

**Comment by vigneshshanmugam** [comment]
@kuisathaverat Sure Thanks, I have done a dummy commit to trigger build

**Comment by graphaelli** [comment]
jenkins, retest this please

**Comment by vigneshshanmugam** [comment]
@graphaelli right now it goes to the default path and we are using the default timeout for the healthcheck. Probably we can run healthcheck on another port just to keep the instance running without getting killed by race between load gen and healthcheck on same port.

**Comment by graphaelli** [comment]
jenkins, retest this please

**Comment by graphaelli** [comment]
@vigneshshanmugam now the CI is actually able to run the services, the failures indicate this was branched before a few fixes went in.  I've merged master in and pushed to your branch, I hope you don't mind.  We should squash merge when this is ready to go.

Also, please disregard my comment about the healthcheck, I was referring to the rum agent container (used by integration tests) and this only changes the opbeans rum container.

**Comment by vigneshshanmugam** [comment]
@graphaelli Thanks a lot for taking care of the broken build.. Sure no problem 👍. I will squash and merge the PR now.

**Pull request merged**
