### PR TITLE
add --apm-server-record option

### PR DESCRIPTION
**Pull request by graphaelli**
for logging payloads sent to apm-server

~for use with~ replaces #565

Sample usage:
```
# launch env
$ ./scripts/compose.py start master --with-opbeans-go --apm-server-record
# export events
$ docker-compose exec apm-server-2 cp /app/events.json .
# watch events live
$ docker-compose exec apm-server-2 tail -f /app/events.json
{"method":"GET","time":"2019-07-30T17:20:40.046920908Z","url":"/config/v1/agents"}
{"body":"{\"metadata\":{\"system\":{\"architecture\":\"amd64\",\"container\":{\"id\":\"5c26fa8518...

```

### CODE REVIEW

**Comment by graphaelli** [comment]
@sqren I took some shortcuts to get this working but nothing too offensive to prevent merging.  Please give it a spin when time permits and feel free to merge / push changes as you see fit.

**Comment by sqren** [comment]
fwiw I had to do the following to copy events.json from the container to the host:
```
docker cp localtesting_8.0.0_apm-server-2:/app/events.json .
```

It seems the other command just copies within the container

**Comment by sqren** [comment]
This works well when I only start a single opbeans agent but if I run `--all` it pretty much grinds to a halt and any docker commands take forever (literally: I've not yet see any of them complete yet :D)

**Comment by graphaelli** [comment]
Sorry about the delay and bad instructions @sqren.  You're right, that `docker-compose cp` is busted and your way is right.  I've just pushed a fix for the recorder that was causing the issues you experienced.

**Comment by sqren** [comment]
@graphaelli When I run `--all --apm-server-record` it is because I want to capture data from all agents. I do not care about elasticsearch, apm-server, kibana or any beats.
Would it make sense that by default running `--apm-server-record` would start all agents and `teeproxy` but nothing else? i'd assume that would make the data collection step a bit faster.

**Comment by graphaelli** [comment]
> Would it make sense that by default running --apm-server-record would start all agents and teeproxy but nothing else?

I added a commit to this to allow use of the apm-server file output, so this should do it:

```
./scripts/compose.py start master --apm-server-record --apm-server-output=file --no-kibana --no-elasticsearch --all
```

**Comment by sqren** [comment]
Awesome, thanks!

**Pull request merged**
