### PR TITLE
feat: APM server managed on 8+ II

### PR DESCRIPTION
**Pull request by kuisathaverat**
## What does this PR do?

* It adds support to launch APM server in a real managed mode for 8+

## Why is it important?

Maintaining compatibility with launching the APM Server managed in 7.x and 8+ is complicated. So it adds a new service ApmManaged to run the Elastic Agent with APM integration configured. This is the default configuration with 8+

test 7.x
```
./scripts/compose.py start 7.16.0
curl -L 127.0.0.1:8200
```

test 8+
```
./scripts/compose.py start 8.0.0
curl -L 127.0.0.1:8200
```

test Opbeans
```
./scripts/compose.py start 8.2.0 --snapshot --with-opbeans-go 
```

test APM Server from sources
```
./scripts/compose.py start 8.2.0 --apm-managed-build https://github.com/elastic/apm-server.git@main
```

closes https://github.com/elastic/apm-integration-testing/issues/1434 https://github.com/elastic/apm-integration-testing/issues/1440

### CODE REVIEW

**Comment by kuisathaverat** [comment]
this works on 8.0.0 and 8.1.0, also with 8.2.0 commits with more than 5 days

**Comment by kuisathaverat** [comment]
The issue we faced yesterday was related to timeout errors to the registry service, not related with the code Today it works again without any modification.

**Review by v1v — APPROVED** [review]

**Pull request merged**
